pub const MINECRAFT_WORDS: [&str; 2048] = [
    "axe", "pick", "craft", "mine", "build",  "stone", "ore", "wood", "tree", "dirt",
    "sand", "grass", "water", "lava", "cave", "torch", "fire", "bow", "arrow", "sword", "mob",
    "cow", "sheep", "pig", "chicken", "wolf", "zombie", "creeper", "enderman", "skeleton", "spider",
    "dungeon", "chest", "portal", "nether", "end", "villager", "farm", "crop", "wheat",
    "carrot", "potato", "beet",  "pumpkin", "fish", "boat", "brew", "pot", "enchant",
    "book", "armor", "helmet", "chestplate", "leggings", "boots", "shield", "pickaxe", "shovel",
    "hoe", "anvil", "furnace", "crafting", "table", "bed", "map", "compass", "clock", "redstone",
    "lever", "button", "pressure", "plate",  "minecart", "bucket", "glass", "brick",
    "coal", "gold", "emerald", "quartz", "obsidian", "netherite", "ghast", "ender", "dragon", "wither",
    "elixir", "potion", "splash", "health", "strength", "speed", "jump", "night", "vision",
    "regeneration", "dye", "wool", "color", "ladder", "fence", "golem", "slime", "magmacube",
    "experience", "xp", "book", "bottle", "bookshelf", "bedrock", "carpet", "banner", "flower",
    "animal", "egg", "cake", "pie", "bread", "cookie",  "slice", "soup", "bone", "meat", "fish",
    "pear", "berry", "honey", "hive", "composter", "furnace", "smelt", "pane", "lamp", "lantern",
    "flint", "steel", "iron",  "diamond", "trapdoor", "dispenser", "dropper",
    "hopper", "observer", "comparator", "repeater", "target", "bell", "jungle", "oak", "birch",
    "spruce", "acacia", "dark", "planks", "log", "stick", "charcoal", "bamboo", "sugar", "cane",
    "meal", "scute", "nether", "star", "saddle", "fishing", "glowstone", "dust", "magma",
    "chorb", "prominent", "medieval", "village", "stronghold", "temple", "desert",
    "wart", "spectral", "bottle", "powder", "scute", "enchanted", "waxed", "weathered", "copper", "block",
    "epic", "legendary", "rare", "mythic", "ancient", "relic", "warden", "axolotl", "goat",
    "chorbening", "chorbia", "lightning", "night", "day", "sky"
];
